# Multistaged Docker build um eine klare struktur des back- und frontends zu bekommen
services:
  backend:
    build: ./backend
    container_name: spordle-backend
    ports:
      - "5050:5000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:////app/data/spordle.db

  frontend:
    build: ./frontend
    container_name: spordle-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5050/api